### ISSUE TITLE
Request and Response should be analyzed with their implementation

### ISSUE THREAD

**Issue by Slamdunk** [Slamdunk/phpstan-zend-framework#3]
@ondrejmirtes anywhere in zend-framework there are typehintes on some interfaces, but the implementations have more API than corresponding interfaces.
Trivial example:
```php
interface A {}
class MyA {
    public function foo();
}
function (A $a) {
    $a->foo();
}
```
Gets correctly:
```
 ------ ---------------------------------------
  Line   tmp.php
 ------ ---------------------------------------
  6      Call to an undefined method A::foo(). 
 ------ ---------------------------------------
```
The issue is that I can't change nor refactor an entire framework; but I have during the inspection the real implementation, so I would like to tell PHPStan to use `MyA` implementation wherever it finds a `A` interface.

Is this possible? May you give me a hit on how?

**Comment by ondrejmirtes** [comment]
What I usually do in this case is that I try to typehint the specific class as soon as possible. In this case, why don't you typehint `MyA` in the anonymous function?

```php
function (MyA $a) {
    $a->foo();
}
```

Usually, what this means is that when I call a method from a framework with a not-enough-precise typehint, I usually override this method in a child class and put a more precise typehint there. Alternatively, you can do this:

```php
function (A $a) {
    assert($a instanceof MyA);
    $a->foo();
}
```

**Comment by Slamdunk** [comment]
Ok, thank you
